# Maven

# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- main

pool:
  vmImage: windows-latest

steps:
- task: PowerShell@2
  inputs:
    targetType: inline
    script: |
              Invoke-WebRequest https://downloads.lambdatest.com/hyperexecute/windows/hyperexecute.exe
              dir 
              set HTTP_PROXY=http://203.74.125.18:8888 
              ./hyperexecute.exe -u ${env:LT_USERNAME} -k ${env:LT_ACCESS_KEY} -i hyperexecuteStatic.yaml --vars "Test=2"
           
           
           
           
- script: |
           echo "Test" 
